name: XGBoost

trainer:
  hyper_params:
    seed: 42
    eta: 
      - 0.1
      - 0.01
      - 0.001
    num_round: 1000
    max_depth:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    min_child_weight:
    - 1
    - 2
    - 3
    - 4
    - 5
    gamma:
    - 0.0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    colsample_bytree:
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
    subsample:
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
    is_used_raw_data:
        - true
    debug: false
    
hydra:
    run:
        dir:  ./configs/${name}/${now:%Y-%m-%d}/${now:%H-%M-%S}